# Generated by Django 6.0.3 on 2026-04-20 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
                ('modify', models.DateField(auto_now=True, verbose_name='Updated')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('peito', 'Peito'), ('costas', 'Costas'), ('perna', 'Perna'), ('ombro', 'Ombro'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('abdomen', 'Abdômen'), ('cardio', 'Cardio')], max_length=30, verbose_name='Categoria')),
                ('difficulty', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', max_length=20, verbose_name='Nível')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
                ('modify', models.DateField(auto_now=True, verbose_name='Updated')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('day', models.CharField(choices=[('segunda', 'Segunda'), ('terca', 'Terça'), ('quarta', 'Quarta'), ('quinta', 'Quinta'), ('sexta', 'Sexta'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='treinos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TreinoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
                ('modify', models.DateField(auto_now=True, verbose_name='Updated')),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
                ('series', models.IntegerField(default=3)),
                ('repetitions', models.IntegerField(default=12)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rest_seconds', models.IntegerField(default=60)),
                ('order', models.IntegerField(default=1)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercicio')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.treino')),
            ],
            options={
                'unique_together': {('treino', 'order')},
            },
        ),
    ]
